[package]
name = "kvs"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.1"
